name: Build, Push, and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy-to-droplet
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push front-end image
        working-directory: front-end
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/ArdaBakici/Taskbank:front-end \
            -t ghcr.io/ArdaBakici/Taskbank:front-end-latest \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.description=Taskbank Front-end" \
            --label "org.opencontainers.image.licenses=MIT" \
            -f Dockerfile . --push

      - name: Build and push back-end image
        working-directory: back-end
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          BUILD_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          BUILD_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          BUILD_IMAGE="ghcr.io/ArdaBakici/Taskbank:back-end@${GITHUB_SHA}"

          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/ArdaBakici/Taskbank:back-end \
            -t ghcr.io/ArdaBakici/Taskbank:back-end-latest \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.description=Taskbank Back-end" \
            --label "org.opencontainers.image.licenses=MIT" \
            --build-arg BUILD_SHA="${SHORT_SHA}" \
            --build-arg BUILD_URL="${BUILD_URL}" \
            --build-arg BUILD_TIME="${BUILD_TIME}" \
            --build-arg BUILD_IMAGE="${BUILD_IMAGE}" \
            -f Dockerfile . --push